insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (1, 1, 1, 'Beer - Molson Excel', 'Goiás');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (2, 2, 2, 'Veal - Ground', 'Langob');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (3, 3, 3, 'Beer - True North Lager', 'Sumbergayam');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (4, 4, 4, 'Oats Large Flake', 'Asamboka');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (5, 5, 5, 'Flounder - Fresh', 'Neyrīz');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (6, 6, 6, 'Longos - Grilled Veg Sandwiches', 'Yanda Bayo');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (7, 7, 7, 'Pepper - Orange', 'Trenton');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (8, 8, 8, 'Pop Shoppe Cream Soda', 'Vittel');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (9, 9, 9, 'Tomatoes - Vine Ripe, Yellow', 'Bangbayang');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (10, 10, 10, 'Shrimp - Black Tiger 26/30', 'Vychegodskiy');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (11, 11, 11, 'Lid - 0090 Clear', 'Sterlibashevo');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (12, 12, 12, 'Cookies - Amaretto', 'Dualing');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (13, 13, 13, 'Wine - Manischewitz Concord', 'Sumurasin');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (14, 14, 14, 'Island Oasis - Pina Colada', 'Zoumaling');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (15, 15, 15, 'Campari', 'Lanta Timur');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (16, 16, 16, 'Daikon Radish', 'Jiangwakou');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (17, 17, 17, 'Cheese - Boursin, Garlic / Herbs', 'Pimbalayan');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (18, 18, 18, 'Wine - Red, Mosaic Zweigelt', 'San Jerónimo');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (19, 19, 19, 'Croissants Thaw And Serve', 'Siaton');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (20, 20, 20, 'Coconut - Shredded, Unsweet', 'Villa Bisonó');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (21, 21, 21, 'Creme De Menth - White', 'Catungawan Sur');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (22, 22, 22, 'Lemonade - Kiwi, 591 Ml', 'Diên Khánh');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (23, 23, 23, 'Wine - Tribal Sauvignon', 'Santo Ângelo');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (24, 24, 24, 'Beef - Bones, Marrow', 'Luoxi');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (25, 25, 25, 'Juice - V8 Splash', 'Castro');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (26, 26, 26, 'Flour - Buckwheat, Dark', 'Pertunmaa');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (27, 27, 27, 'Mcgillicuddy Vanilla Schnap', 'Morropón');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (28, 28, 28, 'Eggplant Oriental', 'Woja');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (29, 29, 29, 'Quail - Jumbo', 'Songshu');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (30, 30, 30, 'Cheese - Provolone', 'Agkathiá');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (31, 31, 31, 'Pork Loin Cutlets', 'Toronto');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (32, 32, 32, 'Lettuce - Treviso', 'Banjar Tibubiyu Kaja');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (33, 33, 33, 'Butter Ripple - Phillips', 'L''Aigle');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (34, 34, 34, 'Tahini Paste', 'Bogoroditsk');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (35, 35, 35, 'Lamb - Shoulder', 'Shishan');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (36, 36, 36, 'Juice - Orange, Concentrate', 'Hushi');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (37, 37, 37, 'Hot Chocolate - Individual', 'Yangmadao');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (38, 38, 38, 'Rum - Spiced, Captain Morgan', 'Jinsha');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (39, 39, 39, 'Pork - Back Ribs', 'Hualmay');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (40, 40, 40, 'Lamb - Leg, Bone In', 'Moguqi');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (41, 41, 41, 'Vaccum Bag 10x13', 'Pasirjengkol');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (42, 42, 42, 'Ecolab Crystal Fusion', 'Tabwakea Village');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (43, 43, 43, 'Molasses - Fancy', 'Fontem');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (44, 44, 44, 'Butter Balls Salted', 'Gabú');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (45, 45, 45, 'Veal - Brisket, Provimi, Bone - In', 'Cape Coast');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (46, 46, 46, 'Roe - Lump Fish, Black', 'Longkou');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (47, 47, 47, 'Sugar - Brown', 'Brandfort');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (48, 48, 48, 'Dates', 'Kadubadak');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (49, 49, 49, 'Beef - Montreal Smoked Brisket', 'Beylagan');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (50, 50, 50, 'Beer - Tetleys', 'Kovel’');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (51, 51, 51, 'Wine - Alsace Gewurztraminer', 'Santa Marta');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (52, 52, 52, 'Amarula Cream', 'Tsiombe');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (53, 53, 53, 'Coconut - Whole', 'Lecong');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (54, 54, 54, 'Mcgillicuddy Vanilla Schnap', 'Zelenogorsk');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (55, 55, 55, 'Coffee - Hazelnut Cream', 'København');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (56, 56, 56, 'Crawfish', 'Alarobia');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (57, 57, 57, 'Lid - High Heat, Super Clear', 'Nusajaya');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (58, 58, 58, 'Chocolate - Sugar Free Semi Choc', 'Shiyuetian');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (59, 59, 59, 'Juice - Orange, Concentrate', 'Barreiros');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (60, 60, 60, 'Beer - Rickards Red', 'Onsala');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (61, 61, 61, 'Lobster - Tail, 3 - 4 Oz', 'Mladá Boleslav');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (62, 62, 62, 'Sobe - Berry Energy', 'Nida');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (63, 63, 63, 'Wine - Cotes Du Rhone', 'Wahawaha');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (64, 64, 64, 'Sauce - Soya, Dark', 'Priob’ye');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (65, 65, 65, 'Lettuce - California Mix', 'Laweueng');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (66, 66, 66, 'Dawn Professionl Pot And Pan', 'Morrelgonj');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (67, 67, 67, 'Lemon Balm - Fresh', 'Yotala');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (68, 68, 68, 'Bread - Olive', 'Tejakalapa');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (69, 69, 69, 'Bread - Assorted Rolls', 'Zhongzhai');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (70, 70, 70, 'Tomatoes - Cherry', 'Ujmisht');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (71, 71, 71, 'Yogurt - Blueberry, 175 Gr', 'Halmstad');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (72, 72, 72, 'Scallops - In Shell', 'Arklow');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (73, 73, 73, 'Soup - Knorr, Chicken Noodle', 'Helsingborg');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (74, 74, 74, 'Muffin Carrot - Individual', 'Brčko');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (75, 75, 75, 'Puree - Raspberry', 'Margara');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (76, 76, 76, 'Water - Mineral, Carbonated', 'Kedatuan');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (77, 77, 77, 'Bar Special K', 'Montepuez');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (78, 78, 78, 'Beans - Black Bean, Preserved', 'Hakodate');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (79, 79, 79, 'Cake - Dulce De Leche', 'El Aïoun');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (80, 80, 80, 'Cheese - Roquefort Pappillon', 'Dugulubgey');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (81, 81, 81, 'Nescafe - Frothy French Vanilla', 'Jangkungkusumo');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (82, 82, 82, 'Pie Shell - 5', 'Si That');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (83, 83, 83, 'Cheese - St. Andre', 'Troyan');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (84, 84, 84, 'Tart Shells - Sweet, 3', 'Postoloprty');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (85, 85, 85, 'Red Pepper Paste', 'Igarassu');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (86, 86, 86, 'Apples - Sliced / Wedge', 'Huoshaoping');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (87, 87, 87, 'Nori Sea Weed', 'Épernay');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (88, 88, 88, 'Icecream - Dstk Cml And Fdg', 'Lanxi');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (89, 89, 89, 'Oil - Margarine', 'Kherson');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (90, 90, 90, 'Bread - Hot Dog Buns', 'Saint Paul');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (91, 91, 91, 'Juice - Orange', 'Midland');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (92, 92, 92, 'Asparagus - Green, Fresh', 'Malaba');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (93, 93, 93, 'Marzipan 50/50', 'Senggreng');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (94, 94, 94, 'Eggplant Italian', 'Paris 07');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (95, 95, 95, 'Potatoes - Mini Red', 'Muquiyauyo');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (96, 96, 96, 'Lychee - Canned', 'Port Said');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (97, 97, 97, 'Kiwano', 'Botshabelo');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (98, 98, 98, 'Chicken - Tenderloin', 'Skaryszew');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (99, 99, 99, 'Calypso - Pineapple Passion', 'Nanshan');
insert into kompanija (osoba_id, vlasnik_id, kompanija_id, naziv, grad) values (100, 100, 100, 'Otomegusa Dashi Konbu', 'Xinhe');
