insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (1, 'Jared', 'Britee', 'Female', '12/26/2021', 'Radomin');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (2, 'Dolli', 'Blasio', 'Male', '3/17/2021', 'Buenavista');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (3, 'Ilise', 'Sarfatti', 'Male', '7/21/2021', 'Ulety');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (4, 'Rockie', 'Gaule', 'Female', '4/27/2021', 'Polešovice');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (5, 'Chauncey', 'Eirwin', 'Male', '9/23/2021', 'Mawlaik');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (6, 'Dniren', 'Paradis', 'Female', '1/16/2021', 'Cilegong');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (7, 'Nobie', 'Walkden', 'Male', '5/8/2021', 'Yuankeng');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (8, 'Tatiana', 'McPhillips', 'Female', '3/19/2021', 'Clifden');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (9, 'Caroline', 'Ovise', 'Female', '12/25/2021', 'Rolante');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (10, 'Armin', 'Ragsdall', 'Male', '11/17/2021', 'Nsok');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (11, 'Marcellus', 'Carous', 'Male', '10/8/2021', 'Quba');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (12, 'Vivyanne', 'Albone', 'Female', '6/4/2021', 'San Vicente Centenario');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (13, 'Trixie', 'Columbine', 'Female', '5/2/2021', 'Wingham');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (14, 'Corrie', 'Baynes', 'Male', '11/11/2021', 'Dili');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (15, 'Waylen', 'Worsley', 'Male', '5/21/2021', 'Shitun');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (16, 'Modesta', 'Serridge', 'Male', '7/21/2021', 'Los Angeles');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (17, 'Cacilia', 'Ezzle', 'Female', '6/16/2021', 'Trail');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (18, 'Sayre', 'Abelovitz', 'Genderqueer', '3/24/2021', 'Quillabamba');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (19, 'Margarethe', 'Fendley', 'Polygender', '8/19/2021', 'Khirbat Tīn Nūr');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (20, 'Etienne', 'Gumey', 'Genderqueer', '2/6/2021', 'Połomia');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (21, 'Cleveland', 'Gravells', 'Female', '7/1/2021', 'Bogorejo');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (22, 'Kizzie', 'Foulcher', 'Female', '1/28/2021', 'Gejiu');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (23, 'Marshall', 'Mascall', 'Female', '11/13/2021', 'Omoku');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (24, 'Josy', 'Baggallay', 'Male', '3/23/2021', 'Balucawi');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (25, 'Philly', 'Matchitt', 'Male', '9/6/2021', 'Namyang-dong');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (26, 'Brunhilda', 'Sinott', 'Female', '7/22/2021', 'Budapest');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (27, 'Mela', 'Claremont', 'Female', '2/12/2021', 'Jiuxian');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (28, 'Wilona', 'Hars', 'Female', '11/1/2021', 'Helsingborg');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (29, 'Regan', 'Donn', 'Female', '7/6/2021', 'Pedraza La Vieja');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (30, 'Pedro', 'Soot', 'Female', '5/28/2021', 'Binucayan');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (31, 'Theodoric', 'Tickner', 'Female', '2/13/2021', 'Pucacaca');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (32, 'Tiena', 'Cutts', 'Female', '1/27/2021', 'Bayanbulag');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (33, 'Ruthie', 'Colby', 'Agender', '11/28/2021', 'Talitsy');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (34, 'Domingo', 'O''Bradden', 'Female', '1/18/2021', '‘Uzeir');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (35, 'Oona', 'Dikes', 'Female', '10/21/2021', 'Jiucaigou');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (36, 'Tuckie', 'Cheke', 'Male', '4/27/2021', 'Chistopol’');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (37, 'Faina', 'Boome', 'Female', '3/25/2021', 'Bellevue');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (38, 'Roderigo', 'Bellard', 'Male', '1/10/2022', 'Ngrambitan');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (39, 'Rinaldo', 'Beldam', 'Male', '12/21/2021', 'Xiongbei');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (40, 'Margi', 'Donaway', 'Female', '8/22/2021', 'Taradale');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (41, 'Jobye', 'Fruish', 'Female', '11/26/2021', 'Wincrange');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (42, 'Alysa', 'Farrow', 'Male', '6/8/2021', 'Pantanal');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (43, 'Jud', 'Anand', 'Male', '4/24/2021', 'Rawa');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (44, 'Bonni', 'Rehor', 'Female', '4/29/2021', 'Kathmandu');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (45, 'Celle', 'Lack', 'Genderfluid', '5/2/2021', 'Lancaster');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (46, 'Dennie', 'Troutbeck', 'Female', '9/1/2021', 'Iporá');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (47, 'Dotti', 'MacCostigan', 'Female', '12/28/2021', 'Belopa');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (48, 'Salmon', 'Whate', 'Male', '2/4/2021', 'Xiuying');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (49, 'Andy', 'Anglim', 'Female', '10/11/2021', 'Las Animas');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (50, 'Adella', 'Traves', 'Female', '10/6/2021', 'Ţāqchah Khānah');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (51, 'Karrie', 'Rignall', 'Male', '6/29/2021', 'Olsztynek');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (52, 'Jilli', 'Rugge', 'Male', '4/30/2021', 'Juigalpa');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (53, 'Joann', 'Smythe', 'Female', '1/10/2022', 'Sisŏphŏn');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (54, 'Art', 'Qusklay', 'Male', '6/5/2021', 'Basqal');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (55, 'Bruno', 'Throughton', 'Female', '8/30/2021', 'Sabaneta');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (56, 'Fey', 'McGuirk', 'Female', '6/2/2021', 'Praia da Vitória');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (57, 'Anna-diana', 'Verdon', 'Female', '12/2/2021', 'Hongsipu');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (58, 'Leigh', 'Cottingham', 'Female', '2/28/2021', 'Lanxi');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (59, 'Emeline', 'Langtree', 'Male', '7/28/2021', 'Baton Rouge');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (60, 'Janaye', 'Boskell', 'Female', '4/8/2021', 'Hetian');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (61, 'Brendis', 'Braybrook', 'Male', '5/18/2021', 'Akat Amnuai');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (62, 'Murry', 'Tomczykiewicz', 'Female', '2/13/2021', 'Okahandja');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (63, 'Kristien', 'Indruch', 'Male', '2/3/2021', 'Besançon');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (64, 'Ilka', 'Cranke', 'Female', '12/25/2021', 'Guantang');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (65, 'Isak', 'McCann', 'Agender', '9/8/2021', 'Nicosia');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (66, 'Courtney', 'Winkell', 'Female', '12/8/2021', 'Titay');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (67, 'Kennedy', 'Sute', 'Female', '11/20/2021', 'Changgang');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (68, 'Cosette', 'Stonebanks', 'Male', '2/16/2021', 'Xishaping');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (69, 'Katee', 'Dunseath', 'Female', '10/24/2021', 'Plaški');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (70, 'Al', 'Hablet', 'Genderqueer', '1/3/2022', 'Banī Khaddāsh');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (71, 'Amory', 'Segebrecht', 'Male', '6/14/2021', 'Gällivare');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (72, 'Belicia', 'Leile', 'Female', '12/2/2021', 'Taungoo');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (73, 'Sheba', 'Filchakov', 'Female', '8/11/2021', 'Camp Thorel');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (74, 'Aubrie', 'Hartil', 'Female', '1/23/2021', 'Mumen');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (75, 'Lorri', 'Chance', 'Female', '5/28/2021', 'Kcynia');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (76, 'Byrann', 'Basnett', 'Female', '6/11/2021', 'Warsaw');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (77, 'Mic', 'Grevile', 'Female', '2/11/2021', 'Nanjin');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (78, 'Willey', 'Veillard', 'Female', '4/6/2021', 'Paris 01');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (79, 'Isidore', 'Caseri', 'Male', '11/26/2021', 'Tālīn');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (80, 'Sydney', 'Zimek', 'Male', '3/16/2021', 'Rawa');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (81, 'Ryann', 'Warrener', 'Male', '1/21/2021', 'Bujaków');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (82, 'Hobart', 'Jopson', 'Female', '7/26/2021', 'Wutongkou');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (83, 'Sandi', 'Budgeon', 'Male', '1/24/2021', 'Xiaqiao');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (84, 'Dorelle', 'Cleynaert', 'Female', '1/23/2021', 'Plužine');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (85, 'Jose', 'Masser', 'Male', '12/12/2021', 'Ban Pong');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (86, 'Marlow', 'Paty', 'Female', '8/29/2021', 'Namayingo');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (87, 'Rochella', 'Busk', 'Male', '12/13/2021', 'Mishan');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (88, 'Alisha', 'MacMenamie', 'Male', '9/23/2021', 'Agat Village');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (89, 'Stepha', 'Hubber', 'Female', '9/2/2021', 'Néa Péramos');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (90, 'Hannah', 'Bellefant', 'Genderfluid', '1/26/2021', 'Kafr Qūd');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (91, 'Iorgo', 'Thowless', 'Male', '11/11/2021', 'Yangdian');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (92, 'Conny', 'Crosio', 'Male', '9/23/2021', 'Suhopolje');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (93, 'Bernardina', 'Cleverly', 'Male', '11/13/2021', 'Melbourne');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (94, 'Parsifal', 'Mower', 'Polygender', '9/10/2021', 'Danbury');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (95, 'Averell', 'Jindrich', 'Male', '2/8/2021', 'Sanjia');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (96, 'Larina', 'Stive', 'Male', '1/31/2021', 'Dallas');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (97, 'Salomon', 'Shade', 'Male', '11/26/2021', 'Vladikavkaz');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (98, 'Teodorico', 'Dragonette', 'Male', '5/28/2021', 'Roubaix');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (99, 'Robinette', 'Bonifas', 'Female', '2/11/2021', 'Girardot');
insert into osoba (osoba_id , ime, prezime, pol, godina_rodjenja, mesto) values (100, 'Margy', 'Davidovits', 'Female', '6/4/2021', 'Nanxia');
