CREATE TABLE offices (office_code INTEGER AUTO_INCREMENT NOT NULL, address VARCHAR(255), city VARCHAR(255), country VARCHAR(255), phone VARCHAR(255), postal_code INTEGER, state VARCHAR(255), territory VARCHAR(255), PRIMARY KEY (office_code))
CREATE TABLE productilnes (product_line INTEGER AUTO_INCREMENT NOT NULL, html_description VARCHAR(255), image VARCHAR(255), text_description VARCHAR(255), code INTEGER, PRIMARY KEY (product_line))
CREATE TABLE employees (employee_number INTEGER AUTO_INCREMENT NOT NULL, email VARCHAR(255), extension VARCHAR(255), first_name VARCHAR(255), job_title VARCHAR(255), last_name VARCHAR(255), office_code INTEGER, reports_to VARCHAR(255), customer_number INTEGER, parent_employee INTEGER, PRIMARY KEY (employee_number))
CREATE TABLE orders (order_ INTEGER NOT NULL, comment VARCHAR(255), customer_number INTEGER, date DATE, required_date DATE, shipped_date DATE, status VARCHAR(255), PRIMARY KEY (order_))
CREATE TABLE products (code INTEGER AUTO_INCREMENT NOT NULL, buy_price FLOAT, description VARCHAR(255), line INTEGER, msrp INTEGER, name VARCHAR(255), quantity_in_stock INTEGER, scale INTEGER, vendor INTEGER, PRIMARY KEY (code))
CREATE TABLE order_details (details_id INTEGER AUTO_INCREMENT NOT NULL, order_line_number INTEGER, price_each INTEGER, quantity_ordered INTEGER, code INTEGER, order_number INTEGER, PRIMARY KEY (details_id))
CREATE TABLE customers (customer_number INTEGER AUTO_INCREMENT NOT NULL, address VARCHAR(255), city VARCHAR(255), contact VARCHAR(255), country VARCHAR(255), credit_limit FLOAT, name VARCHAR(255), phone VARCHAR(255), postal_code INTEGER, sales_rep_employee_number INTEGER, state VARCHAR(255), PRIMARY KEY (customer_number))
CREATE TABLE payments (check_number INTEGER AUTO_INCREMENT NOT NULL, amount INTEGER, payment__date DATE, customer_number INTEGER, PRIMARY KEY (check_number))
ALTER TABLE productilnes ADD CONSTRAINT FK_productilnes_code FOREIGN KEY (code) REFERENCES products (code)
ALTER TABLE employees ADD CONSTRAINT FK_employees_parent_employee FOREIGN KEY (parent_employee) REFERENCES employees (employee_number)
ALTER TABLE employees ADD CONSTRAINT FK_employees_customer_number FOREIGN KEY (customer_number) REFERENCES customers (customer_number)
ALTER TABLE order_details ADD CONSTRAINT FK_order_details_order_number FOREIGN KEY (order_number) REFERENCES orders (order_)
ALTER TABLE order_details ADD CONSTRAINT FK_order_details_code FOREIGN KEY (code) REFERENCES products (code)
ALTER TABLE payments ADD CONSTRAINT FK_payments_customer_number FOREIGN KEY (customer_number) REFERENCES customers (customer_number)
